name: Build and Release

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ensure this matches the Node.js version your project uses

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List build directory contents
      run: ls -la build/
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload .app for macOS
      if: matrix.os == 'macos-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/TJ-DORM-WIFI-Helper-1.0.0-arm64.dmg
        asset_name: TJ-DORM-WIFI-Helper-arm64.dmg
        asset_content_type: application/octet-stream

    - name: Upload .exe for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/TJ-DORM-WIFI-Helper-1.0.0.exe
        asset_name: TJ-DORM-WIFI-Helper.exe
        asset_content_type: application/octet-stream